version: 2.1
jobs:
  # for build
  build:
    docker:
      - image: circleci/node:13.8.0
    steps:
      - checkout
      - run:
          command: npm i
      - run:
          name: "Build"
          command: npm run lint 
  # for test
  test:
    docker:
      - image: circleci/node:13.8.0
    steps:
      - checkout
      - run:
          command: npm i     
      - run:
          name: "Test"
          command: npm run test
  # for analyze
  analyze:
    docker:
      - image: circleci/node:13.8.0
    steps:
      - checkout
      - run:
          command: npm i
      - run:
          name: "Test"
          command: npm audit
  
      
workflows:
  say-hello-workflow:
    jobs:
      - build
      - test:
          requires:
            - build
      - analyze:
          requires:
            - test
